[package]
name="logmover-remote"
version="0.0.0"
edition="2018"

[lib]
name="logmover_remote"
path="lib.rs"

[[bin]]
name="logmover-remote"
path="main.rs"

[[bin]]
name="relocate-test"
path="tests/relocation-test.rs"

[dependencies]
chrono="0.4"
colored="2.0.0"